- name: Add auditd plugin config
  ansible.builtin.template:
    # https://gitlab.com/devopsworks/tools/auditship/-/raw/master/auditship.plugin.conf?ref_type=heads
    src: auditship.plugin.conf.j2
    dest: /etc/audit/plugins.d/auditship.conf
    owner: root
    group: root
    mode: '0640'
  notify: 
    - Restart auditd

- name: Add auditship plugin config
  ansible.builtin.template:
    # https://gitlab.com/devopsworks/tools/auditship/-/raw/master/auditship.plugin.conf?ref_type=heads
    src: auditship.conf.j2
    dest: /etc/auditship.conf
    owner: root
    group: root
    mode: '0640'
  notify: 
    - Restart auditd

- name: Add logrotate config
  ansible.builtin.template:
    url: auditship.logrotate.j2
    dest: /etc/logrotate.d/auditship
    owner: root
    group: root
    mode: '0644'

- name: Check if Telegraf configuration directory exists
  ansible.builtin.stat:
    path: /etc/telegraf/telegraf.d
  register: __auditship_telegraf_dir

- name: Deploy Telegraf Prometheus configuration for auditship
  ansible.builtin.template:
    src: telegraf_prometheus_auditship.conf.j2
    dest: /etc/telegraf/telegraf.d/auditship.conf
    owner: root
    group: root
    mode: '0644'
  when: 
    - auditship_metrics_enabled | bool
    - __auditship_telegraf_dir.stat.exists
    - __auditship_telegraf_dir.stat.isdir
  notify:
    - Restart telegraf
