- name: Finds latest auditship version
  ansible.builtin.uri:
    url: https://gitlab.com/api/v4/projects/71363433/releases
    status_code:
      - 200
  register: __auditship_repo_info
  check_mode: false

- name: Set auditship version facts
  ansible.builtin.set_fact:
    __auditship_latest_version: '{{ __auditship_repo_info.json.0["name"] }}'
    __auditship_latest_num_version: '{{ __auditship_repo_info.json.0["name"] | regex_replace("v","") }}'

- name: Fetches latest version
  ansible.builtin.get_url:
    url: >
      https://gitlab.com/api/v4/projects/71363433/packages/generic/auditship/{{ __auditship_latest_num_version }}/auditship-linux-amd64-{{ __auditship_latest_version }}.gz
    dest: /tmp/auditship.gz
    mode: '0644'
  register: __auditship_fetch
  notify: 
    - Restart auditd

- name: Stop auditd so auditship can be written
  ansible.builtin.service:
    name: auditd
    state: stopped
  when: ansible_virtualization_type not in ["docker","podman"] and __auditship_fetch is changed
  notify: 
    - Restart auditd

- name: Fetch & unarchive auditship
  # can not use unarchive, does not support gz
  ansible.builtin.shell: gunzip -cd /tmp/auditship.gz > /usr/local/bin/auditship && chmod 755 /usr/local/bin/auditship
  changed_when: true
  when: __auditship_fetch is changed
