---
- name: Restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted
  when: ansible_virtualization_type not in ["docker","podman"]

- name: Restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted
  when: ansible_virtualization_type not in ["docker","podman"]
