---
- name: Restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted
  when: ansible_facts['virtualization_type'] | default('') not in ["docker", "podman"]

- name: Restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted
  when: ansible_facts['virtualization_type'] | default('') not in ["docker", "podman"]
